"""baseline schema

Revision ID: 7d57d7dfc357
Revises: 
Create Date: 2026-07-11 19:40:55.324193

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7d57d7dfc357'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('feedback',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('message', sa.String(length=2000), nullable=False),
    sa.Column('page', sa.String(length=300), nullable=True),
    sa.Column('contact', sa.String(length=200), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('ip_hash', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('feedback', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_feedback_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_feedback_status'), ['status'], unique=False)

    op.create_table('readings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('sensor_id', sa.String(length=128), nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lon', sa.Float(), nullable=True),
    sa.Column('pm1_0', sa.Float(), nullable=True),
    sa.Column('pm2_5', sa.Float(), nullable=True),
    sa.Column('pm10', sa.Float(), nullable=True),
    sa.Column('aqi', sa.Float(), nullable=True),
    sa.Column('voc', sa.Float(), nullable=True),
    sa.Column('temperature', sa.Float(), nullable=True),
    sa.Column('humidity', sa.Float(), nullable=True),
    sa.Column('pressure', sa.Float(), nullable=True),
    sa.Column('pm2_5_a', sa.Float(), nullable=True),
    sa.Column('pm2_5_b', sa.Float(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('count_0_3', sa.Float(), nullable=True),
    sa.Column('count_0_5', sa.Float(), nullable=True),
    sa.Column('count_1_0', sa.Float(), nullable=True),
    sa.Column('count_2_5', sa.Float(), nullable=True),
    sa.Column('count_5_0', sa.Float(), nullable=True),
    sa.Column('count_10_0', sa.Float(), nullable=True),
    sa.Column('quality', sa.String(length=16), nullable=False),
    sa.Column('raw', sa.JSON(), nullable=False),
    sa.Column('ingested_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source', 'sensor_id', 'ts', name='uq_reading_source_sensor_ts')
    )
    with op.batch_alter_table('readings', schema=None) as batch_op:
        batch_op.create_index('ix_reading_sensor_ts', ['sensor_id', 'ts'], unique=False)
        batch_op.create_index(batch_op.f('ix_readings_sensor_id'), ['sensor_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_readings_source'), ['source'], unique=False)
        batch_op.create_index(batch_op.f('ix_readings_ts'), ['ts'], unique=False)

    op.create_table('readings_community',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('report_id', sa.Integer(), nullable=True),
    sa.Column('domain', sa.String(length=32), nullable=False),
    sa.Column('parameter', sa.String(length=64), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('unit', sa.String(length=32), nullable=False),
    sa.Column('method', sa.String(length=200), nullable=True),
    sa.Column('taken_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lon', sa.Float(), nullable=True),
    sa.Column('verified', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('readings_community', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_readings_community_report_id'), ['report_id'], unique=False)

    op.create_table('reports',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('domain', sa.String(length=32), nullable=False),
    sa.Column('category', sa.String(length=64), nullable=False),
    sa.Column('description', sa.String(length=2000), nullable=False),
    sa.Column('lat', sa.Float(), nullable=False),
    sa.Column('lon', sa.Float(), nullable=False),
    sa.Column('area_label', sa.String(length=120), nullable=True),
    sa.Column('stage', sa.String(length=24), nullable=False),
    sa.Column('screen_reason', sa.String(length=120), nullable=True),
    sa.Column('flags_count', sa.Integer(), nullable=False),
    sa.Column('verified_by', sa.String(length=120), nullable=True),
    sa.Column('suspected_org', sa.String(length=200), nullable=True),
    sa.Column('org_public', sa.Boolean(), nullable=False),
    sa.Column('photo_path', sa.String(length=300), nullable=True),
    sa.Column('photo_ok', sa.Boolean(), nullable=False),
    sa.Column('contact_email', sa.String(length=200), nullable=True),
    sa.Column('contact_phone', sa.String(length=40), nullable=True),
    sa.Column('ip_hash', sa.String(length=64), nullable=True),
    sa.Column('mod_note', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_reports_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_reports_domain'), ['domain'], unique=False)
        batch_op.create_index(batch_op.f('ix_reports_stage'), ['stage'], unique=False)

    op.create_table('subscriptions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('channel', sa.String(length=16), nullable=False),
    sa.Column('target', sa.String(length=256), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('sensor_id', sa.String(length=128), nullable=True),
    sa.Column('field', sa.String(length=32), nullable=False),
    sa.Column('threshold', sa.Float(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('min_interval_seconds', sa.Integer(), nullable=False),
    sa.Column('quiet_start', sa.Integer(), nullable=True),
    sa.Column('quiet_end', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_notified_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('subscriptions')
    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reports_stage'))
        batch_op.drop_index(batch_op.f('ix_reports_domain'))
        batch_op.drop_index(batch_op.f('ix_reports_created_at'))

    op.drop_table('reports')
    with op.batch_alter_table('readings_community', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_readings_community_report_id'))

    op.drop_table('readings_community')
    with op.batch_alter_table('readings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_readings_ts'))
        batch_op.drop_index(batch_op.f('ix_readings_source'))
        batch_op.drop_index(batch_op.f('ix_readings_sensor_id'))
        batch_op.drop_index('ix_reading_sensor_ts')

    op.drop_table('readings')
    with op.batch_alter_table('feedback', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_feedback_status'))
        batch_op.drop_index(batch_op.f('ix_feedback_created_at'))

    op.drop_table('feedback')
    # ### end Alembic commands ###
