"""Regenerate the documented pollution-source layer from EPA public records.

Pulls EPA TRI (Toxics Release Inventory) facilities for WV via the keyless
Envirofacts REST API, filters to the Kanawha Valley area near our sensors,
converts the DMS-encoded coordinates, and merges them with the curated seed.
Everything is public-record + cited, per docs/SOURCE-POLICY.md.

    python scripts/fetch_sources.py
"""

from __future__ import annotations

import json
from pathlib import Path

import httpx

# Kanawha Valley bounding box (near our Create WV sensors).
LAT_MIN, LAT_MAX = 38.05, 38.65
LON_MIN, LON_MAX = -82.10, -81.30

# Hand-verified landmark seed (kept first; EPA facilities are appended).
CURATED = {
    "_comment": "DOCUMENTED pollution sources — public-record facilities plotted for context only. Per docs/SOURCE-POLICY.md: factual, cited, neutral; NOT an assertion that a facility caused any sensor reading. Curated landmarks + EPA TRI (Kanawha Valley bbox), regenerated by scripts/fetch_sources.py.",
    "tier": "documented",
    "disclaimer": "Locations are public-record industrial facilities shown for perspective near community sensors. Presence on this map is not a claim that a facility caused any measured pollution.",
    "sources": [
        {"name": "John Amos Power Plant", "type": "Coal-fired power plant",
         "operator": "Appalachian Power (AEP)", "lat": 38.4728, "lon": -81.8236,
         "citation": "EPA FRS / EIA-860 (public record)"},
        {"name": "Belle chemical plant (Chemours, former DuPont)", "type": "Chemical manufacturing",
         "operator": "Chemours", "lat": 38.235, "lon": -81.548,
         "citation": "EPA FRS / TRI (public record)"},
    ],
}


def _dms_to_decimal(v) -> float | None:
    """EPA fac_latitude/longitude are integers encoded DDMMSS (e.g. 371729)."""
    try:
        n = abs(int(v))
    except (TypeError, ValueError):
        return None
    if n == 0:
        return None
    ss, mm, dd = n % 100, (n // 100) % 100, n // 10000
    return dd + mm / 60 + ss / 3600


def fetch_wv_tri() -> list[dict]:
    rows = []
    url = "https://data.epa.gov/efservice/tri_facility/state_abbr/WV/rows/{}:{}/JSON"
    for start in range(0, 800, 200):
        r = httpx.get(url.format(start, start + 199), timeout=60)
        r.raise_for_status()
        batch = r.json()
        rows.extend(batch)
        if len(batch) < 200:
            break
    return rows


def to_source(rec: dict) -> dict | None:
    if str(rec.get("fac_closed_ind") or "") == "1":
        return None
    lat = _dms_to_decimal(rec.get("fac_latitude"))
    lon = _dms_to_decimal(rec.get("fac_longitude"))
    if lat is None or lon is None:
        return None
    lon = -abs(lon)  # WV is western hemisphere
    if not (LAT_MIN <= lat <= LAT_MAX and LON_MIN <= lon <= LON_MAX):
        return None
    op = (rec.get("standardized_parent_company") or rec.get("parent_co_name") or "").strip()
    operator = op.title() if op and op.upper() not in ("NA", "N/A", "NONE") else None
    return {
        "name": (rec.get("facility_name") or "").title().strip(),
        "type": "TRI-listed facility (reports toxic releases)",
        "operator": operator,
        "lat": round(lat, 4),
        "lon": round(lon, 4),
        "citation": f"EPA TRI (facility {rec.get('tri_facility_id')})",
    }


def main():
    epa = [s for s in (to_source(r) for r in fetch_wv_tri()) if s]
    # dedupe by name; keep curated first (hand-verified landmarks)
    seen = {s["name"].lower() for s in CURATED["sources"]}
    merged = list(CURATED["sources"])
    for s in epa:
        if s["name"] and s["name"].lower() not in seen:
            merged.append(s)
            seen.add(s["name"].lower())
    out = dict(CURATED)
    out["sources"] = merged
    path = Path(__file__).parent.parent / "src/airwv/data/sources.json"
    path.write_text(json.dumps(out, indent=2))
    print(f"EPA TRI in bbox: {len(epa)}   total documented sources: {len(merged)}")


if __name__ == "__main__":
    main()
