"""Regenerate the documented pollution-source layer (EPA TRI emitters) for Sources.

The baseline facility set on the Sources page: EPA Toxics Release Inventory (TRI)
emitters, kept public-record and neutrally framed ("permitted emitter of X", not
"polluter"). Water NPDES dischargers are layered on separately by fetch_water_sources.py.

Source: EPA Envirofacts TRI REST (data.epa.gov/efservice, keyless) for WV + neighboring
states (pollution crosses state lines), clipped to WV's bounding box; DMS coordinates
converted; merged with the curated seed.

    python scripts/fetch_sources.py

Writes src/airwv/data/sources.json, served by /api/sources and shown on the Sources page.
Public-record + cited — see docs/DATA-SOURCES.md.
"""

from __future__ import annotations

import json
import math
from pathlib import Path

import httpx

# Statewide West Virginia bounding box (fast pre-filter before the polygon test).
LAT_MIN, LAT_MAX = 37.10, 40.70
LON_MIN, LON_MAX = -82.70, -77.70

# WV plus every state it borders (OH/PA/MD/VA/KY). WV facilities are all kept;
# neighbor facilities only if within BORDER_BUFFER_KM of the WV line — i.e. "just
# across the border" — so we catch cross-border emitters without pulling whole
# neighboring metros (Pittsburgh, Roanoke) into the map.
STATES = ["WV", "OH", "PA", "MD", "VA", "KY"]
BORDER_BUFFER_KM = 20.0

# Coarse clockwise WV outline (lat, lon). Approximate — used only with the buffer
# above, so ~10km imprecision is absorbed. Traces the northern panhandle, the Ohio
# River (OH), the Big Sandy (KY), the VA ridge, and the eastern panhandle/Potomac.
WV_OUTLINE = [
    (40.64, -80.60), (40.16, -80.52), (39.72, -80.88), (39.34, -81.45),
    (38.99, -81.75), (38.70, -82.13), (38.42, -82.44), (37.78, -82.30),
    (37.30, -81.97), (37.21, -81.55), (37.30, -81.20), (37.53, -80.86),
    (38.00, -80.30), (38.46, -79.68), (38.76, -79.22), (39.00, -78.60),
    (39.32, -77.83), (39.32, -77.72), (39.62, -78.35), (39.72, -79.00),
    (39.72, -80.52), (40.16, -80.52), (40.64, -80.60),
]


def _seg_km(lat, lon, a, b) -> float:
    """Distance (km) from a point to segment a-b via equirectangular projection."""
    latr = math.radians(lat)
    def xy(p):
        return (math.radians(p[1]) * math.cos(latr) * 6371.0, math.radians(p[0]) * 6371.0)
    px, py = math.radians(lon) * math.cos(latr) * 6371.0, math.radians(lat) * 6371.0
    (ax, ay), (bx, by) = xy(a), xy(b)
    dx, dy = bx - ax, by - ay
    seg = dx * dx + dy * dy
    t = 0.0 if seg == 0 else max(0.0, min(1.0, ((px - ax) * dx + (py - ay) * dy) / seg))
    return math.hypot(px - (ax + t * dx), py - (ay + t * dy))


def near_wv_border(lat, lon) -> bool:
    return min(_seg_km(lat, lon, WV_OUTLINE[i], WV_OUTLINE[i + 1])
               for i in range(len(WV_OUTLINE) - 1)) <= BORDER_BUFFER_KM

# Hand-verified landmark seed (kept first; EPA facilities are appended).
CURATED = {
    "_comment": "DOCUMENTED pollution sources — public-record facilities plotted for context only. Per docs/SOURCE-POLICY.md: factual, cited, neutral; NOT an assertion that a facility caused any sensor reading. Curated landmarks + EPA TRI (Kanawha Valley bbox), regenerated by scripts/fetch_sources.py.",
    "tier": "documented",
    "disclaimer": "Locations are public-record industrial facilities shown for perspective near community sensors. Presence on this map is not a claim that a facility caused any measured pollution.",
    "sources": [
        {"name": "John Amos Power Plant", "type": "Coal-fired power plant",
         "operator": "Appalachian Power (AEP)", "lat": 38.4728, "lon": -81.8236,
         "citation": "EPA FRS / EIA-860 (public record)"},
        {"name": "Belle chemical plant (Chemours, former DuPont)", "type": "Chemical manufacturing",
         "operator": "Chemours", "lat": 38.235, "lon": -81.548,
         "citation": "EPA FRS / TRI (public record)"},
    ],
}


def _dms_to_decimal(v) -> float | None:
    """EPA fac_latitude/longitude are integers encoded DDMMSS (e.g. 371729)."""
    try:
        n = abs(int(v))
    except (TypeError, ValueError):
        return None
    if n == 0:
        return None
    ss, mm, dd = n % 100, (n // 100) % 100, n // 10000
    return dd + mm / 60 + ss / 3600


def fetch_state_tri(state: str) -> list[dict]:
    rows = []
    url = f"https://data.epa.gov/efservice/tri_facility/state_abbr/{state}/rows/{{}}:{{}}/JSON"
    for start in range(0, 6000, 200):
        r = httpx.get(url.format(start, start + 199), timeout=60)
        r.raise_for_status()
        batch = r.json()
        rows.extend(batch)
        if len(batch) < 200:
            break
    return rows


def categorize(name: str, ftype: str = "", operator: str = "") -> str:
    """Best-effort category from the facility name/type (keyword rules, first match).

    Coarse but useful for map filtering; refine later with NAICS/industry codes.
    """
    s = f"{name} {operator} {ftype}".upper()

    def has(*ks):
        return any(k in s for k in ks)

    # coal/mining/processing first, so a coal prep plant run by an "…Energy" company
    # isn't miscaught as power
    if has("COAL", "MINING", " MINE", "PREPARATION", "PREP PLANT", "PROCESSING", "COKE",
           "QUARRY", "STEEL", "ALUMIN", "SMELT", "FOUNDRY", "ALLOY", "CEMENT", "GLASS"):
        return "materials"
    if has("POWER PLANT", "POWER STATION", "POWER CO", "ELECTRIC POWER", "GENERATING",
           "GENERATION", "MON POWER", "APPALACHIAN POWER", "POWER LLC"):
        return "power"
    if has("CHEMICAL", "CHEMOURS", "DUPONT", "DOW ", "BAYER", "COVESTRO", "UNION CARBIDE",
           "SPECIALTY", "POLYMER", "PLASTIC", "RESIN", "AGRI", "FERTILIZER"):
        return "chemical"
    if has("GAS", "OIL", "PETROLEUM", "PIPELINE", "COMPRESSOR", "MIDSTREAM", "REFIN",
           "EQT", "ANTERO", "MPLX", "MARATHON", "WELL"):
        return "oil_gas"
    if has("LANDFILL", "WASTE", "DISPOSAL", "RECYCL", "SANITAT"):
        return "waste"
    return "other"


def to_source(rec: dict) -> dict | None:
    if str(rec.get("fac_closed_ind") or "") == "1":
        return None
    lat = _dms_to_decimal(rec.get("fac_latitude"))
    lon = _dms_to_decimal(rec.get("fac_longitude"))
    if lat is None or lon is None:
        return None
    lon = -abs(lon)  # WV is western hemisphere
    if not (LAT_MIN <= lat <= LAT_MAX and LON_MIN <= lon <= LON_MAX):
        return None
    state = (rec.get("state_abbr") or "").upper()
    # WV facilities are all kept; neighbors only if right across the WV line.
    if state != "WV" and not near_wv_border(lat, lon):
        return None
    op = (rec.get("standardized_parent_company") or rec.get("parent_co_name") or "").strip()
    operator = op.title() if op and op.upper() not in ("NA", "N/A", "NONE") else None
    name = (rec.get("facility_name") or "").title().strip()
    return {
        "name": name,
        "type": "TRI-listed facility (reports toxic releases)",
        "operator": operator,
        "state": state or None,
        "category": categorize(name, "", operator or ""),
        "lat": round(lat, 4),
        "lon": round(lon, 4),
        "citation": f"EPA TRI (facility {rec.get('tri_facility_id')})",
    }


def main():
    epa = []
    for st in STATES:
        found = [s for s in (to_source(r) for r in fetch_state_tri(st)) if s]
        print(f"  {st}: {len(found)} in bbox")
        epa.extend(found)
    # dedupe by name; keep curated first (hand-verified landmarks)
    seen = {s["name"].lower() for s in CURATED["sources"]}
    merged = list(CURATED["sources"])
    for s in epa:
        if s["name"] and s["name"].lower() not in seen:
            merged.append(s)
            seen.add(s["name"].lower())
    out = dict(CURATED)
    out["sources"] = merged
    path = Path(__file__).parent.parent / "src/airwv/data/sources.json"
    path.write_text(json.dumps(out, indent=2))
    print(f"EPA TRI in bbox: {len(epa)}   total documented sources: {len(merged)}")


if __name__ == "__main__":
    main()
